### ISSUE TITLE
Are there any jobs within Sydney

### ISSUE THREAD

**Issue by rustylabs** [RustAU/Sydney#10]
To whom it may concern,

I was wondering if there were any jobs within Sydney regarding Rust related jobs. I have experience in Rust and I was looking to further improve my Rust skills by working for a company that utilises Rust?

**Comment by pinkforest** [comment]
There is a #jobs channel in our Discord: https://discord.gg/pW35BNSBeV

**Comment by rustylabs** [comment]
@pinkforest Thanks man!

**Comment by pinkforest** [comment]
Please don't call me man k? :)
