### ISSUE TITLE
Really Little Misdirection

### ISSUE THREAD

**Issue by Tahinli** [RustAU/Sydney#37]
I'm not sure if it's done by purpose but here is a little arrow misdirection in this pr https://github.com/RustAU/Sydney/pull/36, if I'm not wrong.

<img width="697" alt="image" src="https://github.com/RustAU/Sydney/assets/96421894/9a010813-7c25-46d7-83b2-6422ee645d95">

Raw mode disables I/O instead of entering alternate screen as official document says:
<img width="341" alt="image" src="https://github.com/RustAU/Sydney/assets/96421894/e3e9e8c7-6ba0-4706-b41a-e2b10c117acb">

I'm pretty sure @orhun knows better than me. Big Respect.

**Comment by orhun** [comment]
Good catch! Fixed in the slides, thanks for reporting <3
